Fix redirection bug.
Had ampersand on wrong side of redirection operator.

diff --git a/package b/package
--- a/package
+++ b/package
@@ -31,7 +31,7 @@ for element in "$@"; do
 		cpu_one)
 			CPU_ONE=true;;
 		*)
-			echo "Invalid argument: $element" &>2
+			echo "Invalid argument: $element" >&2
 			exit 1;;
 	esac
 done
