Make `start` accept multiple workfiles.

diff --git a/scripts/client/start b/scripts/client/start
--- a/scripts/client/start
+++ b/scripts/client/start
@@ -1,7 +1,6 @@
 #!/bin/bash
 #
-# gracefully stop the process 
-# param 1: process id
+# Start the specified workfiles
 
 # Quit if any command fails or if a variable is unbound
 set -e -o nounset
@@ -12,41 +11,23 @@ SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
 [ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
 source "${SCRIPT_DIR}/env.sh"
 
-if [ $# -eq 1 ]; then
-	echo starting process workfile $1
+function die () {
+	[ -n "$1" ] && echo "$1" >&2
+	exit 1
+}
+
+while [ "$#" -ne 0 ]; do
+	echo "Processing workfile: $1"
+	WORKFILE="$( basename "$1" )"
+
 	if [ $RHOST ]; then
-		LINE1="scp $1 $RHOST:$DPATH/work/$1.tmp"
-		LINE2="ssh $RHOST 'mv $DPATH/work/$1.tmp $DPATH/work/$1'"
+		scp "$1" "$RHOST:$DPATH/work/$WORKFILE.tmp" || die "Unable to send workfile to managment node"
+		ssh "$RHOST" "mv '$DPATH/work/$WORKFILE.tmp $DPATH/work/$WORKFILE'" || die "Failed to submit workfile"
 	else
-		LINE1="true"
-		LINE2="cp $1 $DPATH/work/"
+		stat "$1" || die "Unable to send workfile to managment node"
+		cp "$1" "$DPATH/work/" || die "Failed to submit workfile"
 	fi
 
-	eval $LINE1
-	if [ $? -eq 0 ]; then
-		eval $LINE2
-	else
-		echo Failed to submit workfile
-	fi;
-elif [ $# -eq 2  ]; then
-	echo starting process workfile $1/$2
-	if [ $RHOST ]; then
-		LINE1="scp $1/$2 $RHOST:$DPATH/work/$2.tmp"
-		LINE2="ssh $RHOST 'mv $DPATH/work/$2.tmp $DPATH/work/$2'"
-	else
-		LINE1="true"
-		LINE2="cp $1/$2 $DPATH/work/"
-	fi
-
-	eval $LINE1
-	if [ $? -eq 0 ]; then
-		eval $LINE2
-	else
-		echo Failed to submit workfile
-	fi;
-else
-        echo "usage: ./start <work file>"
-	echo "or: ./start <path to> <work file>"
-fi;
-
+	shift
+done
 
